### ISSUE TITLE
Support unserialization of unresolved Nodes

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-java#43]
When unserializating a reference to a Node with do not know about unserialize by instantiating a special subclass of Node (BrokenNode?)

In case of multiple references to the same unresolve node-id, return the same instance of BrokenNode.

**Comment by ftomassetti** [comment]
We have now two APIs: low-level and high-level. The high-level one expects to be able to solve references, while the lower-level one does not attempt to solve references. I think this covers this requirement. What do you think @enikao ?

**Comment by enikao** [comment]
I agree, low-level/high-level covers this.
