### ISSUE TITLE
Align with latest decisions (early March 2023)

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-java#46]
"Inspired" by https://github.com/LIonWeb-org/lioncore-typescript/issues/48

- [x] https://github.com/LIonWeb-org/organization/issues/93
- [x] https://github.com/LIonWeb-org/organization/issues/92 (waiting for decision)
- [x] https://github.com/LIonWeb-org/organization/issues/91 (PR #56)
- [x] https://github.com/LIonWeb-org/organization/issues/90
- [x] https://github.com/LIonWeb-org/organization/issues/89
- [x] https://github.com/LIonWeb-org/organization/issues/86 (not yet confirmed)

**Comment by ftomassetti** [comment]
I should change the type of Metamodel.version from string to integer

**Comment by dslmeinte** [comment]
Didn't we agree for `Metamodel.version` to be a `string`?

**Comment by enikao** [comment]
It might even be both:
* `integer` in M3
* `string` in all places in serialization format

(just showing options here, not an expression of opinion/preference)
