### ISSUE TITLE
serializer duplicates nodes

### ISSUE THREAD

**Issue by enikao** [LIonWeb-org/lioncore-java#52]
I'm exporting this model:
![image](https://user-images.githubusercontent.com/2211690/227736537-fd1c00fc-23c8-4c38-a0bd-0c2e5b6c603a.png)

It contains 3 nodes.
However, the output contains the book twice: [line 38](https://github.com/LIonWeb-org/lioncore-mps/blob/niko/importer/solutions/io.lionweb.mps.json.test/resources/bobs-library.json#L38) and [line 81](https://github.com/LIonWeb-org/lioncore-mps/blob/niko/importer/solutions/io.lionweb.mps.json.test/resources/bobs-library.json#L81)

using v0.0.6 of lioncore-java

**Comment by ftomassetti** [comment]
Can you help me learn how to reproduce this?

**Comment by ftomassetti** [comment]
The problem is caused by calling serializeTreesToJson and passing two trees, one being a subtree of the other tree

**Comment by ftomassetti** [comment]
This should now be solved in master. We can close this issue once @enikao had time to check that it works also with his test case in MPS

**Comment by enikao** [comment]
works, fixed
