### ISSUE TITLE
Why does EnumerationLiteral not have getKey()?

### ISSUE THREAD

**Issue by enikao** [LIonWeb-org/lioncore-java#53]
All other M3 members have such a method.

**Comment by ftomassetti** [comment]
Right, I will add it

**Comment by ftomassetti** [comment]
mmm, but where would we use the EnumerationLiteral key?
Would it be used for properties having as value an enumeration?

For example:

```
        {
          "property": {
            "metamodel": "metamodel_id",
            "version": "1",
            "key": "property_of_type_enum_key"
          },
          "value": "my_enum_literal_key"
        }
```

**Comment by dslmeinte** [comment]
As usual, enums are weird :) We could use the `key` to refer to an enum literal, the alternative being the `id`. I think using the `key` is more consistent.

**Comment by enikao** [comment]
I agree `key` would be better.
Rationale: We cross between M1 -> M2. Any time we do this, we use `key`. If we stay on the same metalevel, we use `id`.

**Comment by enikao** [comment]
https://github.com/LIonWeb-org/organization/issues/128
