### ISSUE TITLE
Typo: setname()

### ISSUE THREAD

**Issue by enikao** [LIonWeb-org/lioncore-java#58]
[`Feature.setname()`](https://github.com/LIonWeb-org/lioncore-java/blob/be030f022d840dcd9eae9e04e58a0a1c5f2a7522/core/src/main/java/org/lionweb/lioncore/java/metamodel/Feature.java#L80) should probably be `setName()`

**Comment by ftomassetti** [comment]
This was the case also for EnumerationLiteral. Thank you for spotting this. I solved it on master directly
